import dark from './vars/spectrum-dark';
import light from './vars/spectrum-light';
import darkest from './vars/spectrum-darkest';
import lightest from './vars/spectrum-lightest';
import medium from './vars/spectrum-medium';
import large from './vars/spectrum-large';
import global from './vars/spectrum-global';

const palette = { dark, darkest, light, lightest };
const scale = { medium, large };

export const tokens = { global, palette, scale };

export { default as well } from './components/well';
export { default as underlay } from './components/underlay';
export { default as typography } from './components/typography';
export { default as treeview } from './components/treeview';
export { default as tray } from './components/tray';
export { default as tooltip } from './components/tooltip';
export { default as toggle } from './components/toggle';
export { default as toast } from './components/toast';
export { default as textfield } from './components/textfield';
export { default as tags } from './components/tags';
export { default as tabs } from './components/tabs';
export { default as table } from './components/table';
export { default as stepper } from './components/stepper';
export { default as steplist } from './components/steplist';
export { default as statuslight } from './components/statuslight';
export { default as splitview } from './components/splitview';
export { default as splitbutton } from './components/splitbutton';
export { default as slider } from './components/slider';
export { default as sidenav } from './components/sidenav';
export { default as searchwithin } from './components/searchwithin';
export { default as search } from './components/search';
export { default as rule } from './components/rule';
export { default as rating } from './components/rating';
export { default as radio } from './components/radio';
export { default as quickaction } from './components/quickaction';
export { default as popover } from './components/popover';
export { default as pagination } from './components/pagination';
export { default as page } from './components/page';
export { default as modal } from './components/modal';
export { default as miller } from './components/miller';
export { default as menu } from './components/menu';
export { default as link } from './components/link';
export { default as label } from './components/label';
export { default as inputgroup } from './components/inputgroup';
export { default as image } from './components/image';
export { default as illustratedmessage } from './components/illustratedmessage';
export { default as icon } from './components/icon';
export { default as helptext } from './components/helptext';
export { default as fieldlabel } from './components/fieldlabel';
export { default as fieldgroup } from './components/fieldgroup';
export { default as dropzone } from './components/dropzone';
export { default as dropindicator } from './components/dropindicator';
export { default as dropdown } from './components/dropdown';
export { default as dialog } from './components/dialog';
export { default as cyclebutton } from './components/cyclebutton';
export { default as colorwheel } from './components/colorwheel';
export { default as colorslider } from './components/colorslider';
export { default as colorloupe } from './components/colorloupe';
export { default as colorhandle } from './components/colorhandle';
export { default as colorarea } from './components/colorarea';
export { default as coachmark } from './components/coachmark';
export { default as circleloader } from './components/circleloader';
export { default as checkbox } from './components/checkbox';
export { default as card } from './components/card';
export { default as calendar } from './components/calendar';
export { default as buttongroup } from './components/buttongroup';
export { default as button } from './components/button';
export { default as breadcrumb } from './components/breadcrumb';
export { default as barloader } from './components/barloader';
export { default as banner } from './components/banner';
export { default as avatar } from './components/avatar';
export { default as assetlist } from './components/assetlist';
export { default as asset } from './components/asset';
export { default as alert } from './components/alert';
export { default as actionmenu } from './components/actionmenu';
export { default as actiongroup } from './components/actiongroup';
export { default as accordion } from './components/accordion';
